# Generated by Django 3.2.8 on 2021-10-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discount',
            new_name='Descuento',
        ),
    ]
