# Generated by Django 3.2.8 on 2021-10-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20211010_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='titulo',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
