# Generated by Django 3.2.8 on 2021-10-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20211010_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='url_foto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
