# Generated by Django 3.2.8 on 2021-10-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_categoria_url_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(blank=True, upload_to='Categoria'),
        ),
    ]
