# Generated by Django 3.2.8 on 2021-10-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_categoria_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descuento',
            name='titulo',
        ),
        migrations.AddField(
            model_name='producto',
            name='url_foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
