# Generated by Django 3.2.8 on 2021-10-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_auto_20211010_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(blank=True, upload_to='Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, upload_to='Producto'),
        ),
    ]
