# Generated by Django 3.2.8 on 2021-10-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
