# Generated by Django 3.2.8 on 2021-10-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='notas',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
