# Generated by Django 3.2.8 on 2021-10-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='comensales',
            field=models.IntegerField(default=1, verbose_name='Numero de comensales'),
            preserve_default=False,
        ),
    ]
