# Generated by Django 3.2.8 on 2021-10-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_reserva_comensales'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha de la reserva'),
        ),
    ]
